import type { Category, Quest, QuestPack } from "../../types";
import { learningQuests } from "./learning";

export const photos = {
  forest:
    "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=85",
  shadows:
    "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=900&q=85",
  art: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=900&q=85",
  city: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1000&q=85",
  coffee:
    "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=900&q=85",
  coast:
    "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?auto=format&fit=crop&w=1000&q=85",
  books:
    "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=900&q=85",
  friends:
    "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85",
};
type Seed = [
  string,
  string,
  Category,
  number,
  string,
  string[],
  string[],
  string[],
  string?,
  string?,
];
const seeds: Seed[] = [
  [
    "shadow-hunter",
    "Shadow hunter",
    "Explore",
    20,
    "Find and photograph five interesting shadows hiding in plain sight.",
    [
      "Find a geometric shadow",
      "Find a natural shadow",
      "Find a moving shadow",
      "Find a strange shadow",
      "Photograph your favorite",
    ],
    ["Camera or phone"],
    ["Outside", "Campus", "City"],
    photos.shadows,
    "Photography",
  ],
  [
    "ugly-poster",
    "The ugly poster challenge",
    "Create",
    20,
    "One font. Two colors. Absolutely no pressure to make it perfect.",
    [
      "Pick a random theme from a nearby object",
      "Choose one font and two colors",
      "Make a poster in 20 minutes",
      "Keep the imperfect part you like most",
    ],
    ["Paper and pens or a design app"],
    ["Home", "Campus"],
    photos.art,
    "Design",
  ],
  [
    "micro-adventure",
    "Take the unfamiliar turn",
    "Explore",
    30,
    "A tiny detour can change the way you see your neighborhood.",
    [
      "Choose a familiar, public starting point",
      "Take a safe route you usually pass by",
      "Walk for ten minutes and notice something new",
      "Photograph or sketch one discovery",
      "Make your way back",
    ],
    ["Comfortable shoes"],
    ["Outside", "City", "Campus"],
    photos.forest,
    "Walking",
  ],
  [
    "color-story",
    "A color story",
    "Create",
    15,
    "Choose a color. Find it in five unexpected places.",
    [
      "Pick a color before you begin",
      "Find five objects in that color",
      "Photograph them from different angles",
      "Arrange the pictures into a small color story",
    ],
    ["Camera or phone"],
    ["Home", "Outside", "City"],
    photos.art,
    "Photography",
  ],
  [
    "six-word",
    "Six words, a whole world",
    "Create",
    5,
    "Tell a complete little story in just six words.",
    [
      "Look at an object near you",
      "Imagine its secret history",
      "Write that history in six words",
      "Give the story a title",
    ],
    ["Paper and pen"],
    ["Home", "Campus"],
    photos.books,
    "Writing",
  ],
  [
    "sound-postcard",
    "Make a sound postcard",
    "Create",
    30,
    "Collect the soundtrack of an ordinary place.",
    [
      "Pick a quiet public spot",
      "Record three short ambient sounds without private conversations",
      "Arrange the clips into a one-minute soundscape",
      "Name your sound postcard",
    ],
    ["Phone with sound recorder"],
    ["Home", "Outside", "Campus"],
    photos.coast,
    "Music",
  ],
  [
    "paper-city",
    "Build a paper city",
    "Create",
    60,
    "Turn yesterday’s packaging into a miniature neighborhood.",
    [
      "Collect clean scrap paper and cardboard",
      "Sketch three building shapes",
      "Fold and assemble your street",
      "Photograph it from street level",
    ],
    ["Scrap paper", "Scissors", "Tape"],
    ["Home"],
    photos.art,
    "DIY",
  ],
  [
    "blind-sketch",
    "Draw without looking",
    "Create",
    15,
    "Let your eyes follow an object while your hand finds its own way.",
    [
      "Choose an interesting object",
      "Keep your eyes on it and draw for three minutes",
      "Repeat from another angle",
      "Add a single color to your favorite sketch",
    ],
    ["Paper and pen"],
    ["Home", "Outside", "Campus"],
    photos.art,
    "Sketching",
  ],
  [
    "one-block",
    "One block, five details",
    "Explore",
    15,
    "A familiar street deserves a second look.",
    [
      "Choose a public street or campus path",
      "Notice a pattern, texture, and old detail",
      "Find something you have never noticed",
      "Record your favorite discovery",
    ],
    ["Comfortable shoes"],
    ["City", "Campus", "Outside"],
    photos.city,
    "Architecture",
  ],
  [
    "green-hour",
    "An hour under the trees",
    "Explore",
    60,
    "Find a nearby green space and explore at your own pace.",
    [
      "Choose an open public park",
      "Bring water and check the route",
      "Follow a marked path",
      "Pause somewhere peaceful",
      "Head back with one detail worth remembering",
    ],
    ["Water", "Comfortable shoes"],
    ["Outside", "City"],
    photos.forest,
    "Nature",
  ],
  [
    "local-tourist",
    "Tourist in your own city",
    "Explore",
    180,
    "Spend an afternoon seeing your city with fresh eyes.",
    [
      "Choose three free public landmarks",
      "Plan a safe walking or transit route",
      "Read one historical sign at each stop",
      "Take one photo at each place",
      "Pick the stop you would show a friend",
    ],
    ["Water", "Map"],
    ["City"],
    photos.city,
    "Travel",
  ],
  [
    "sky-five",
    "Five minutes of sky",
    "Explore",
    5,
    "Look up. There is a whole scene above your usual eye line.",
    [
      "Find a safe place to stop outdoors",
      "Put your phone away for two minutes",
      "Notice a cloud, color, or bird",
      "Describe the sky in one sentence",
    ],
    [],
    ["Outside", "Campus", "City"],
    photos.coast,
    "Nature",
  ],
  [
    "texture-hunt",
    "The texture treasure hunt",
    "Play",
    15,
    "Find the rough, the smooth, and the wonderfully unexpected.",
    [
      "Find something smooth",
      "Find something patterned",
      "Find something weathered",
      "Photograph your three finds without disturbing them",
    ],
    ["Camera or phone"],
    ["Home", "Outside", "Campus"],
    photos.shadows,
    "Scavenger hunt",
  ],
  [
    "coin-story",
    "Let a coin tell the story",
    "Play",
    5,
    "A tiny storytelling game with a very unpredictable narrator.",
    [
      "Choose a character and a place",
      "Flip a coin: heads is good news, tails a complication",
      "Make three flips and tell the story",
      "Give it a surprising ending",
    ],
    ["Coin"],
    ["Home", "Campus"],
    photos.books,
    "Storytelling",
  ],
  [
    "paper-flight",
    "Paper airplane studio",
    "Play",
    30,
    "Try three designs and see which one glides the farthest.",
    [
      "Fold three different paper airplanes",
      "Clear a safe indoor flight path",
      "Test each design three times",
      "Adjust your favorite and fly it again",
    ],
    ["Paper", "Tape measure"],
    ["Home", "Campus"],
    photos.art,
    "Experiment",
  ],
  [
    "gentle-move",
    "Move to one whole song",
    "Play",
    5,
    "Give your body a change of pace with a song you love.",
    [
      "Choose an upbeat song",
      "Clear a comfortable space",
      "Move, stretch, or dance in your own way",
      "Take a breath and notice how you feel",
    ],
    ["Music player"],
    ["Home"],
    photos.friends,
    "Movement",
  ],
  [
    "photo-bingo",
    "Neighborhood photo bingo",
    "Play",
    60,
    "Turn a walk into a friendly search for small surprises.",
    [
      "Write nine things to find, from round windows to yellow doors",
      "Choose a public walking area",
      "Find as many as you can without rushing",
      "Compare your discoveries",
    ],
    ["Camera or phone", "Paper and pen"],
    ["City", "Campus", "Outside"],
    photos.city,
    "Scavenger hunt",
  ],
  [
    "origami",
    "Fold something from nothing",
    "Learn",
    15,
    "Learn one simple origami fold and make it your own.",
    [
      "Find instructions for a paper boat",
      "Fold slowly through each step",
      "Try again from memory",
      "Give your boat a name",
    ],
    ["Square paper"],
    ["Home", "Campus"],
    photos.art,
    "DIY",
  ],
  [
    "new-phrase",
    "A new way to say hello",
    "Learn",
    5,
    "Learn a greeting in a language you have never tried.",
    [
      "Choose a language you are curious about",
      "Find a greeting and listen to its pronunciation",
      "Say it aloud three times",
      "Learn when it is appropriate to use",
    ],
    ["Internet access"],
    ["Home", "Campus"],
    photos.books,
    "Languages",
  ],
  [
    "tree-detective",
    "Meet a neighborhood tree",
    "Learn",
    30,
    "Learn the name and story of a tree you walk past.",
    [
      "Find a tree along a public path",
      "Observe its bark, leaf shape, and size",
      "Use a field guide to identify it",
      "Learn one interesting fact without picking anything",
    ],
    ["Field guide or internet access"],
    ["Outside", "Campus", "City"],
    photos.forest,
    "Nature",
  ],
  [
    "coffee-curious",
    "A more curious cup",
    "Learn",
    15,
    "Turn your next drink into a little sensory experiment.",
    [
      "Prepare your usual tea or coffee",
      "Notice its aroma before tasting",
      "Sip slowly and write down three flavors",
      "Notice what changes as it cools",
    ],
    ["Tea or coffee", "Cup"],
    ["Home"],
    photos.coffee,
    "Food",
  ],
  [
    "museum-hour",
    "One room, one hour",
    "Learn",
    60,
    "Spend time with a single room in a free local museum.",
    [
      "Find a free museum or gallery and check opening hours",
      "Choose one room",
      "Look closely at three pieces",
      "Read their labels and compare impressions",
      "Write one question to explore later",
    ],
    ["Access to a free museum"],
    ["City"],
    photos.shadows,
    "Art",
  ],
  [
    "old-friend",
    "The just-because call",
    "Social",
    15,
    "Reach out to someone you have been meaning to catch up with.",
    [
      "Choose a friend you have not spoken with lately",
      "Ask whether it is a good time to talk",
      "Share one small thing from your week",
      "Ask what has been making them smile",
    ],
    ["Phone"],
    ["Home", "Campus"],
    photos.friends,
    "Connection",
  ],
  [
    "question-swap",
    "Ask a different question",
    "Social",
    5,
    "Skip the usual small talk with someone you know.",
    [
      "Invite a friend to a quick question swap",
      "Ask: what is a tiny thing you changed your mind about?",
      "Listen without planning your answer",
      "Take your turn",
    ],
    ["A willing friend"],
    ["Home", "Campus", "City"],
    photos.friends,
    "Conversation",
  ],
  [
    "cook-together",
    "The shared-table experiment",
    "Social",
    60,
    "Make a simple meal with someone, using what you already have.",
    [
      "Agree on a dish and check allergies",
      "Gather ingredients already on hand",
      "Split the preparation",
      "Cook safely and eat together",
      "Name your accidental specialty",
    ],
    ["A willing friend", "Kitchen", "Ingredients"],
    ["Home"],
    photos.coffee,
    "Cooking",
  ],
  [
    "walk-talk",
    "A walk with no agenda",
    "Social",
    30,
    "Good company, a familiar route, and nothing to accomplish.",
    [
      "Invite someone for a short walk",
      "Choose an accessible public route together",
      "Put phones away when safe",
      "Let the conversation wander",
      "Finish somewhere familiar",
    ],
    ["A willing friend", "Comfortable shoes"],
    ["Outside", "Campus", "City"],
    photos.forest,
    "Walking",
  ],
  [
    "playlist-swap",
    "Trade three songs",
    "Social",
    15,
    "Get to know a friend through the songs they keep coming back to.",
    [
      "Ask a friend to choose three songs",
      "Send three of your own",
      "Listen to one from their selection",
      "Tell them what you noticed",
    ],
    ["A willing friend", "Music player"],
    ["Home", "Campus"],
    photos.friends,
    "Music",
  ],
  [
    "sunset-seat",
    "A front-row seat to sunset",
    "Chill",
    30,
    "The day’s best show does not need a ticket.",
    [
      "Check when the sun sets",
      "Choose a safe, accessible public spot",
      "Arrive with a little time to spare",
      "Watch the colors change without multitasking",
      "Leave before your route becomes unsafe",
    ],
    ["A comfortable layer"],
    ["Outside", "City", "Campus"],
    photos.coast,
    "Nature",
  ],
  [
    "album-break",
    "An album, uninterrupted",
    "Chill",
    60,
    "Listen to a whole album as if it is a place you can visit.",
    [
      "Pick an album you have never heard in full",
      "Settle somewhere comfortable",
      "Put other screens away",
      "Listen all the way through",
      "Keep the song that stayed with you",
    ],
    ["Music player"],
    ["Home"],
    photos.coffee,
    "Music",
  ],
  [
    "window-watch",
    "The window intermission",
    "Chill",
    5,
    "Let the world move for a moment while you stay still.",
    [
      "Sit comfortably near a window",
      "Take three unhurried breaths",
      "Notice five small movements outside",
      "Return when you feel ready",
    ],
    [],
    ["Home", "Campus"],
    photos.forest,
    "Observation",
  ],
  [
    "slow-journal",
    "A page for right now",
    "Chill",
    15,
    "Collect the little details of this very ordinary day.",
    [
      "Write the date at the top of a page",
      "Describe one thing you heard, smelled, and saw",
      "Write a moment you would like to keep",
      "Leave the rest of the page unfinished if you like",
    ],
    ["Paper and pen"],
    ["Home", "Campus"],
    photos.books,
    "Writing",
  ],
  [
    "long-picnic",
    "A very unhurried picnic",
    "Chill",
    120,
    "Pack something simple and make an afternoon of doing less.",
    [
      "Choose a public park and check the weather",
      "Pack food, water, and a blanket",
      "Find a comfortable permitted spot",
      "Eat, read, or watch the world",
      "Take all your litter home",
    ],
    ["Food", "Water", "Blanket"],
    ["Outside"],
    photos.forest,
    "Nature",
  ],
];
export const quests: Quest[] = [
  ...seeds.map<Quest>(
    ([
      id,
      title,
      category,
      duration,
      description,
      steps,
      requirements,
      locationTypes,
      image,
      subcategory,
    ]) => ({
      id,
      title,
      category,
      duration,
      description,
      steps,
      requirements,
      locationTypes,
      coverImage: image || photos.forest,
      subcategory: subcategory || category,
      difficulty:
        duration >= 180
          ? "epic"
          : duration >= 120
            ? "hard"
            : duration >= 60
              ? "medium"
              : "easy",
      energy:
        category === "Chill" || category === "Learn"
          ? "low"
          : category === "Play"
            ? "high"
            : "medium",
      participants:
        category === "Social"
          ? ["friends", "pair"]
          : ["solo", "friends", "pair"],
      budget: "free",
      xp:
        id === "shadow-hunter"
          ? 40
          : duration >= 180
            ? 120
            : duration >= 120
              ? 70
              : duration >= 60
                ? 40
                : 20,
      tags: [category.toLowerCase(), (subcategory || category).toLowerCase()],
      status: "published",
      createdAt: "2026-09-01T00:00:00.000Z",
      ...(locationTypes.some((l) => ["Outside", "City"].includes(l))
        ? {
            safetyNote:
              "Use public, accessible spaces. Stay aware of your surroundings, respect others’ privacy, and choose a route that feels safe for you.",
          }
        : {}),
    }),
  ),
  ...learningQuests,
];
export const packs: QuestPack[] = [
  {
    id: "creative-reset",
    title: "Creative reset",
    description:
      "Get out of your head and make something. No masterpiece required.",
    image: photos.art,
    color: "peach",
    questIds: [
      "ugly-poster",
      "color-story",
      "six-word",
      "blind-sketch",
      "paper-city",
    ],
  },
  {
    id: "touch-grass",
    title: "A little more outside",
    description:
      "Fresh air, unfamiliar paths, and the things you almost walked past.",
    image: photos.forest,
    color: "sage",
    questIds: [
      "micro-adventure",
      "green-hour",
      "sky-five",
      "tree-detective",
      "sunset-seat",
    ],
  },
  {
    id: "solo-days",
    title: "Your own kind of day",
    description: "Small adventures that are even better in your own company.",
    image: photos.coast,
    color: "blue",
    questIds: [
      "shadow-hunter",
      "coffee-curious",
      "museum-hour",
      "album-break",
      "slow-journal",
    ],
  },
  {
    id: "campus",
    title: "Between classes",
    description: "Turn a little free time into a campus-sized adventure.",
    image: photos.city,
    color: "lavender",
    questIds: [
      "one-block",
      "texture-hunt",
      "photo-bingo",
      "question-swap",
      "walk-talk",
    ],
  },
  {
    id: "no-money",
    title: "Good days, zero budget",
    description: "A reminder that interesting does not have to cost a thing.",
    image: photos.shadows,
    color: "yellow",
    questIds: [
      "sky-five",
      "window-watch",
      "six-word",
      "old-friend",
      "gentle-move",
    ],
  },
  {
    id: "date-night",
    title: "Better together",
    description: "Trade the usual plans for a little shared curiosity.",
    image: photos.friends,
    color: "peach",
    questIds: ["cook-together", "question-swap", "playlist-swap", "walk-talk"],
  },
];
