import type { Quest } from "../../types";

export const learningTopics = [
  "Coding",
  "Languages",
  "Science",
  "Math",
  "Design",
  "Everyday skills",
] as const;
type Lesson = [
  string,
  (typeof learningTopics)[number],
  number,
  string,
  string,
  string,
];
const lessons: Lesson[] = [
  [
    "Variables as labeled boxes",
    "Coding",
    5,
    "A variable names a value. In JavaScript, let score = 2 creates a variable; score = score + 3 changes it to 5.",
    "Trace score = 4; score = score * 2; score = score - 1 on paper.",
    "Explain why the final score is 7, then invent another example.",
  ],
  [
    "Make a decision with if",
    "Coding",
    10,
    "An if statement runs code when a condition is true. if (temperature > 30) chooses temperatures above 30, excluding 30 itself.",
    "Write a rule that labels a score of 50 or more as Pass. Try scores 49, 50, and 51.",
    "Check that you used >= 50 and explain why > 50 would fail at the boundary.",
  ],
  [
    "Trace a loop",
    "Coding",
    15,
    "A loop repeats work. for (let i = 1; i <= 3; i++) visits 1, 2, and 3. A running total starts at 0 and adds each value.",
    "Trace a loop adding 1 through 5. Write the total after each addition.",
    "Your totals should be 1, 3, 6, 10, 15. Explain what changes if the loop starts at 0.",
  ],
  [
    "Turn a recipe into a function",
    "Coding",
    20,
    "A function accepts inputs and returns a result. function double(n) { return n * 2; } produces 8 for double(4). Returning a value differs from printing it.",
    "Write a function rectangleArea(width, height). Trace it with (3, 4), (5, 2), and (0, 8). Paper is enough.",
    "Check the results 12, 10, and 0. Explain which values are inputs and which are outputs.",
  ],
  [
    "Build a tiny HTML page",
    "Coding",
    30,
    "HTML describes structure: <h1> is a main heading, <p> a paragraph, and <ul><li>Item</li></ul> a list. Closing tags use a slash.",
    "Write a page about a hobby with a heading, a paragraph, and a three-item list. Sketch how it would look; optionally open it in a browser.",
    "Check every opening tag has its matching closing tag, and explain why headings describe structure.",
  ],
  [
    "Five Spanish greetings",
    "Languages",
    5,
    "Hola means hello; gracias means thank you; por favor means please; buenos días means good morning; adiós means goodbye.",
    "Read the phrases, cover them, and recall the Spanish for each English meaning.",
    "Use three phrases in a tiny written dialogue, then check spelling against the lesson.",
  ],
  [
    "French numbers one to ten",
    "Languages",
    10,
    "French numbers 1–10 are un, deux, trois, quatre, cinq, six, sept, huit, neuf, dix.",
    "Write a numbered list, cover it, and recall it twice. Then try numbers in random order.",
    "Translate 3, 7, 9, and 10 without looking: trois, sept, neuf, dix.",
  ],
  [
    "Introduce yourself in Spanish",
    "Languages",
    15,
    "Me llamo … means my name is …; Soy de … means I am from …; Me gusta … means I like … when followed by a singular noun or infinitive.",
    "Write three sentences using your name, place, and one activity: leer (to read) or dibujar (to draw). Recall them without looking.",
    "Translate your sentences back to English and check you used Me gusta leer or Me gusta dibujar.",
  ],
  [
    "Learn five useful Japanese phrases",
    "Languages",
    20,
    "In romanized Japanese: konnichiwa means hello; arigatō means thank you; sumimasen means excuse me or sorry; hai means yes; iie means no. Romanization is a starting point, not a pronunciation guide.",
    "Make five paper or mental flashcards. Practice meaning-to-phrase and phrase-to-meaning, then write two situations for sumimasen.",
    "Recall all five meanings and identify one phrase whose pronunciation you want to check with a native recording later.",
  ],
  [
    "Build a spaced-recall routine",
    "Languages",
    30,
    "Active recall means retrieving an answer before checking it. Spacing means returning to it in later sessions. Use these Spanish words: casa = house, libro = book, agua = water, pan = bread, sol = sun.",
    "Make five cards, test yourself, take a short break, and shuffle before retesting. Spend the break writing a sentence in English using each meaning.",
    "Record which words you recalled correctly and schedule a short review tomorrow. A miss is useful feedback.",
  ],
  [
    "Explain why shadows move",
    "Science",
    5,
    "A shadow forms when an opaque object blocks light. Changing the light source or object position changes the shadow. Earth's rotation makes the Sun appear to move across the sky.",
    "Sketch a lamp, an object, and its shadow. Draw a second lamp position and predict the new shadow direction.",
    "Explain why the shadow points away from the light. Never look directly at the Sun.",
  ],
  [
    "Draw the water cycle",
    "Science",
    10,
    "Evaporation turns liquid water into vapor. Condensation forms liquid droplets from vapor. Precipitation returns water from clouds; runoff and infiltration move it over and into the ground.",
    "Draw a landscape and connect these processes with labeled arrows. Include the Sun as an energy source.",
    "Explain the difference between water vapor and the tiny liquid droplets in a cloud.",
  ],
  [
    "Meet the parts of a cell",
    "Science",
    15,
    "A typical plant or animal cell has a membrane controlling exchange, cytoplasm inside, and a nucleus containing most DNA. Plant cells also have a cell wall; photosynthetic plant cells contain chloroplasts.",
    "Draw and label a typical animal cell and a leaf cell. Mark three shared structures and two plant features.",
    "Explain why not every plant cell needs chloroplasts, using roots as an example.",
  ],
  [
    "Design a fair experiment",
    "Science",
    20,
    "A fair comparison changes one intended factor while controlling others. The independent variable is what you change; the dependent variable is what you measure. Repeated trials reveal variation.",
    "Plan a paper-plane experiment comparing two wing shapes. Keep paper, launch method, and location the same; plan five flights per shape.",
    "Name both variables, two controls, and one source of measurement error. You do not need to fly the planes today.",
  ],
  [
    "Build a food web",
    "Science",
    30,
    "Producers capture energy, usually from sunlight. Consumers eat organisms. Decomposers break down dead material. In a food web, arrows often point from food to eater to show energy transfer.",
    "Draw a hypothetical web with grass, seeds, grasshopper, mouse, bird, and hawk. Add decomposers and label each role.",
    "Describe two possible effects of fewer grasshoppers. Distinguish a prediction from something you have observed.",
  ],
  [
    "Find ten percent mentally",
    "Math",
    5,
    "Ten percent is one tenth: divide by 10. Five percent is half of ten percent; twenty percent is twice ten percent.",
    "Find 10%, 5%, and 20% of 240 without a calculator.",
    "Check your answers: 24, 12, 48. Explain the steps to yourself.",
  ],
  [
    "Make equivalent fractions",
    "Math",
    10,
    "Multiplying a fraction's numerator and denominator by the same nonzero number preserves its value: 1/2 = 2/4 = 3/6.",
    "Draw a rectangle showing 1/2, then split it into sixths. Find two fractions equivalent to 2/3.",
    "Check that 4/6 and 6/9 equal 2/3. Explain why adding 1 to both parts does not generally work.",
  ],
  [
    "Mean versus median",
    "Math",
    15,
    "The mean is the sum divided by the count. The median is the middle of sorted values; for an even count, average the two middle values.",
    "Find the mean and median of 2, 3, 3, 4, 18. Replace 18 with 38 and repeat.",
    "The first mean is 6 and the second is 10; both medians are 3. Explain the effect of the large value.",
  ],
  [
    "Solve a two-step equation",
    "Math",
    20,
    "Keep an equation balanced by doing the same operation to both sides. For 2x + 3 = 11, subtract 3, then divide by 2 to get x = 4.",
    "Solve 3x + 2 = 17, 4x - 5 = 7, and 2x + 8 = 0. Write each step.",
    "Check x = 5, 3, and -4 by substituting each into its original equation.",
  ],
  [
    "Count simple probabilities",
    "Math",
    30,
    "For equally likely outcomes, probability is favorable outcomes divided by total outcomes. Two fair coin tosses have four ordered outcomes: HH, HT, TH, TT.",
    "List outcomes for three coin tosses. Count exactly two heads, at least one head, and no heads.",
    "Check probabilities 3/8, 7/8, and 1/8. Explain why HHT and HTH are distinct outcomes.",
  ],
  [
    "Spot visual hierarchy",
    "Design",
    5,
    "Visual hierarchy guides attention through size, weight, spacing, and placement. A large heading and smaller supporting text help communicate reading order.",
    "Sketch a notice with a title, date, and location. Make the most important item stand out with size alone.",
    "Look away and back: which item do you notice first? Explain whether it matches your intended priority.",
  ],
  [
    "Practice alignment",
    "Design",
    10,
    "Alignment connects elements along a shared edge or axis. Consistent alignment helps a layout feel organized and makes scanning easier.",
    "Draw three labels and three values. Try scattered positions, then align labels to one edge and values to another.",
    "Compare both sketches and identify the alignment rule that makes the information easier to scan.",
  ],
  [
    "Create a type scale",
    "Design",
    15,
    "A type scale is a small set of text sizes assigned to roles. For example: title 32, heading 24, body 16. Consistent roles matter more than using many sizes.",
    "Sketch a recipe using only those three sizes or equivalent handwritten proportions. Assign each text block a role.",
    "Check that all text with the same role has the same size. Explain where spacing could replace extra size changes.",
  ],
  [
    "Make color-independent labels",
    "Design",
    20,
    "Color alone should not carry essential meaning. Pair it with text, shape, or an icon so information remains understandable without color.",
    "Design success, warning, and error messages on paper. Give each a label and a distinct symbol, then imagine all three in grayscale.",
    "Check whether every message is still identifiable. Improve any that depend on red, yellow, or green alone.",
  ],
  [
    "Prototype a simple form",
    "Design",
    30,
    "Useful forms have visible labels, clear instructions, and specific error messages. Placeholder text disappears while typing, so it is not a substitute for a label.",
    "Sketch a two-field event signup form, its empty state, a missing-field error, and a success message. Use fictional details.",
    "Ask whether someone can identify required fields and fix each error without guessing. Revise one confusing part.",
  ],
  [
    "Write a clear email subject",
    "Everyday skills",
    5,
    "A useful subject line names the topic and requested action. 'Review poster by Friday' gives more information than 'Important'.",
    "Rewrite three vague subjects: Hello, Question, and Urgent. Invent a specific context for each.",
    "Check each rewrite tells the reader what the message concerns without opening it.",
  ],
  [
    "Turn notes into a checklist",
    "Everyday skills",
    10,
    "An actionable checklist uses observable actions. 'Prepare' is vague; 'Put the notebook in the bag' has a clear finish.",
    "Choose a small routine and write five verb-first actions in order. Split any step that contains several unrelated actions.",
    "Check that another person could tell whether each action is complete.",
  ],
  [
    "Compare unit prices",
    "Everyday skills",
    15,
    "A unit price divides cost by quantity. Compare prices using the same unit: a 500 g pack costing 60 costs 12 per 100 g.",
    "Compare that pack with a 750 g pack costing 96. Then make your own pair of examples.",
    "The second pack costs 12.8 per 100 g, so the first is cheaper per unit. Explain why pack size alone is misleading.",
  ],
  [
    "Evaluate a factual claim",
    "Everyday skills",
    20,
    "Separate a claim from its evidence. Ask who published it, what evidence is shown, when it was produced, and whether an independent source agrees.",
    "Invent an advertising claim and list three pieces of evidence you would need before trusting it. Separate measurable statements from opinions.",
    "Write one question that could disprove the claim. Record what remains unknown instead of guessing.",
  ],
  [
    "Learn with a teach-back",
    "Everyday skills",
    30,
    "Teach-back tests understanding by explaining a concept in your own words, finding gaps, checking them, and trying again. Fluent reading is not the same as recall.",
    "Choose one concept you know. Write a short explanation, add an example, identify two gaps, and revise using notes you already have.",
    "Give a one-minute explanation without notes and write one unanswered question for your next session.",
  ],
];

export const learningQuests: Quest[] = lessons.map(
  ([title, topic, duration, lesson, practice, check], index) => {
    const study = Math.max(1, Math.floor(duration / 3));
    const review = Math.max(1, Math.floor(duration / 5));
    return {
      id: `learning-${index + 1}`,
      title,
      category: "Learn",
      subcategory: topic,
      duration,
      description: lesson,
      steps: [
        `Learn · ${study} min: Read the short lesson above and explain its main idea.`,
        `Practice · ${duration - study - review} min: ${practice}`,
        `Check · ${review} min: ${check}`,
      ],
      difficulty: "easy",
      energy: "low",
      locationTypes: ["Home", "Campus", "Outside", "City"],
      participants: ["solo", "pair", "friends"],
      budget: "free",
      requirements: ["Paper and pen or a notes app"],
      xp: duration >= 20 ? 40 : 20,
      tags: ["learn", topic.toLowerCase(), "timed learning"],
      coverImage:
        "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=900&q=85",
      status: "published",
      createdAt: "2026-10-02T00:00:00.000Z",
    };
  },
);

export function learningMatches(
  topic: string,
  minutes: number,
  completed: string[],
) {
  return learningQuests.filter(
    (q) =>
      (!topic || q.subcategory === topic) &&
      q.duration <= minutes &&
      !completed.includes(q.id),
  );
}
